### ISSUE TITLE
Flat mesh

### ISSUE THREAD

**Issue by mmaechtel** [oscarpilote/Ortho4XP#226]
Hi,

I only get totally flat meshes out of 1.4. I'm sure I changed something, since it worked about 2 weeks ago, but I've run out of ideas what the cause could be. Maybe someone could help me out of my 'flat world' :) Tnx Mike

Batch build launched for a number of 1 tiles.
Dealing with tile  1 / 1 : +47+008

Step 1 : Building vector data for tile +47+008 : 
--------

-> Dealing with airports
    * Recycling OSM data from .\OSM_data\+40+000\+47+008\+47+008_airports.osm.bz2
   EDSI   Segelflugplatz Binningen                                     1 runway , lat= 47.80, lon= 8.72
   EDSL   Flugplatz Blumberg                                           2 runways, lat= 47.84, lon= 8.56
   EDSN   Neuhausen ob Eck Airfield                                    1 runway , lat= 47.98, lon= 8.90
   EDSR   Flugplatz Stahringen-Wahlwies                                1 runway , lat= 47.80, lon= 8.98
   EDTD   Verkehrslandeplatz Donaueschingen-Villingen                  2 runways, lat= 47.97, lon= 8.52
   LSMD   Militärflugplatz Dübendorf                                   2 runways, lat= 47.40, lon= 8.64
   LSME   Militärflugplatz Emmen                                       1 runway , lat= 47.09, lon= 8.30
   LSPF   Sportflugplatz Schmerlat                                     1 runway , lat= 47.69, lon= 8.53
   LSPH   Flugplatz Hegmatten                                          1 runway , lat= 47.51, lon= 8.77
   LSPN   Flugplatz Triengen                                           1 runway , lat= 47.23, lon= 8.08
   LSPV   Flugplatz Wangen-Lachen                                      1 runway , lat= 47.20, lon= 8.87
   LSZF   Flugplatz Birrfeld                                           2 runways, lat= 47.44, lon= 8.23
   LSZH   Zürich Airport                                               4 runways, lat= 47.46, lon= 8.56
   LSZK   Flugplatz Speck-Fehraltorf                                   1 runway , lat= 47.38, lon= 8.76
   LSZN   Hausen am Albis Airfield                                     2 runways, lat= 47.24, lon= 8.52
   LSZO   Flugplatz Beromünster                                        2 runways, lat= 47.19, lon= 8.20
   LSZT   Flugplatz Lommis                                             1 runway , lat= 47.52, lon= 9.00
   LSZU   Flugplatz Buttwil                                            1 runway , lat= 47.26, lon= 8.30
   ****   Segelfluggelände Bohlhof                                     1 runway , lat= 47.65, lon= 8.38
   ****   Segelflugplatz Hilzingen                                     1 runway , lat= 47.76, lon= 8.77
   ****   Segelflugplatz Reiselfingen                                  1 runway , lat= 47.85, lon= 8.37
   ****   ****                                                         1 runway , lat= 47.19, lon= 8.09
   ****   ****                                                         1 runway , lat= 47.56, lon= 8.20
   ****   ****                                                         1 runway , lat= 47.20, lon= 8.96
   Loading elevation data and smoothing it over airports.
    Downloading  .\Elevation_data\+40+000\N47E008.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  .\Elevation_data\+40+000\N47E007.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  .\Elevation_data\+40+000\N47E009.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  .\Elevation_data\+40+000\N46E008.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  .\Elevation_data\+40+000\N46E007.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  .\Elevation_data\+40+000\N46E009.hgt from Viewfinderpanoramas (J. de Ferranti).
    * Min altitude: 0.0 , Max altitude: 1147.0 , Mean: 7.854457
   Patching LSZH.patch.osm
   Auto-patched 29 runways and 173 pieces of taxiway.
   Flattened 76 helipads.
   Number of edges at this point: 22635
-> Dealing with roads
    * Recycling OSM data from .\OSM_data\+40+000\+47+008\+47+008_big_roads.osm.bz2
    * Checking which large roads need levelling.
    * Buffering banked road network as multipolygon.
      Encoding it.
   Number of edges at this point: 47080
-> Dealing with coastline
    * Recycling OSM data from .\OSM_data\+40+000\+47+008\+47+008_coastline.osm.bz2
   Number of edges at this point: 47080
-> Dealing with inland water
    * Recycling OSM data from .\OSM_data\+40+000\+47+008\+47+008_water.osm.bz2
    * Building water multipolygon.
      *  Bodensee will be masked like the sea due to its large area of 532 km^2.
      Cleaning it.
      Encoding it.
      Separate treatment for larger pieces requiring masks.
      Encoding them.
   Number of edges at this point: 108532
-> Inserting edges related to the orthophotos grid
-> Inserting additional boundary edges for gluing
-> Transcription to the files  C:/X-Plane Enhancement/1.4/zOrtho-Experiments\zOrtho4XP_+47+008\Data+47+008.poly and .node

Final number of constrained edges : 152483

Completed in 46.20sec.
_________________________________________________________________________________________________

Step 2 : Building mesh for tile +47+008 : 
--------

-> Modifying curv_tol weight map according to runway locations.
-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from .\OSM_data\+40+000\+47+008\+47+008_coastline.osm.bz2
-> Start of the mesh algorithm Triangle4XP.
   Loading altitudes from DEM file.

   Loading curv_tol geographic weights.

   Computing curvatures from altitudes.

   Constructing Delaunay triangulation by divide-and-conquer method.

   Recovering segments in Delaunay triangulation.

   Spreading regional attributes.

   Adding Steiner points to enforce quality.

   Looking for bad triangles.

   Computing altitude and normal maps.

   Node file C:/X-Plane Enhancement/1.4/zOrtho-Experiments\zOrtho4XP_+47+008\Data+47+008.1.node written to disk.

   Tri file  C:/X-Plane Enhancement/1.4/zOrtho-Experiments\zOrtho4XP_+47+008\Data+47+008.1.ele  written to disk.

   Statistics:

   Input vertices: 128548

   Input segments: 152483

   Input holes: 0

   Mesh vertices: 169,248

                   -----------------

   Mesh triangles: ---> 329,863

                   -----------------

   Mesh edges: 499110

   Mesh exterior boundary edges: 8631

   Mesh interior boundary edges: 157230

   Mesh subsegments (constrained edges): 165861

-> Loading of the mesh computed by Triangle4XP.
-> Post processing of altitudes according to vector data
   Smoothing inland water.
   Smoothing of sea water.
   Treatment of airports, roads and patches.
-> Writing output nodes file.
-> Writing final mesh to the file C:/X-Plane Enhancement/1.4/zOrtho-Experiments\zOrtho4XP_+47+008\Data+47+008.mesh

Completed in 3.72sec.
_________________________________________________________________________________________________

Step 2.5 : Building masks for tile +47+008 : 
--------

-> Deleting existing masks
-> Reading mesh data
-> Deleting existing masks
-> Reading mesh data
   *  C:/X-Plane Enhancement/1.4/zOrtho-Experiments\zOrtho4XP_+47+008\Data+47+008.mesh
-> Construction of the masks
   Created 11424_17184.png
   Created 11408_17200.png
   Created 11408_17184.png
   Created 11424_17200.png
   Created 11440_17184.png
   Created 11440_17200.png

Completed in 4.57sec.
_________________________________________________________________________________________________

Step 3 : Building DSF/Imagery for tile +47+008 : 
--------

-> Initializing providers with potential data on this tile.
-> Checking airport locations for upgraded zoomlevel.
-> Reading mesh file
-> Adapting water triangles to XP12 requirements
-> Computing bathymetry depth ratio bounds based on distance masks
-> Computing point pools and texture requirements
-> Encoding of the DSF file
     Final nbr of nodes: 393846
     Extracting some rasters from X-Plane's Global Scenery
     DSF file encoded, total size is : 16789809 bytes (16.0M)
 *Activating DSF file.

Completed in 16.99sec.
_________________________________________________________________________________________________

Step 4 : Extracting overlay for tile +47+008 : 
--------

-> Making a copy of the original overlay DSF in tmp dir
-> The original DSF is a 7z archive, uncompressing...
-> Converting the copy to text format
     Converting .\tmp\+47+008.dsf from DSF to text as .\tmp\+47+008_tmp_dsf.txt

     File .\tmp\+47+008.dsf had 167 ter, 0 obj, 187 pol, 12 net.

     Converted .\tmp\+47+008.dsf to .\tmp\+47+008_tmp_dsf.txt

-> Selecting overlays for copy/paste
-> Converting back the text DSF to binary format
     Converting .\tmp\+47+008_tmp_dsf_without_mesh.txt from text to DSF as .\tmp\+47+008_tmp_dsf_without_mesh.dsf

     Scanning for dimension properties...

     Got dimension properties, establishing file writer...

     Got entire file, processing and creating DSF.

     Converted .\tmp\+47+008_tmp_dsf_without_mesh.txt to .\tmp\+47+008_tmp_dsf_without_mesh.dsf

-> Coping the final overlay DSF in .\yOrtho4XP_Overlays\Earth nav data\+40+000

Completed in 9.26sec.
_________________________________________________________________________________________________
Batch process completed in 1m20sec

**Comment by d41k4n** [comment]
Please zip and attach (or upload and link to) C:/X-Plane Enhancement/1.4/zOrtho-Experiments\zOrtho4XP_+47+008\Data+47+008.mesh

**Comment by mmaechtel** [comment]
[Ortho4XP_+47+008.zip](https://github.com/oscarpilote/Ortho4XP/files/14550907/Ortho4XP_%2B47%2B008.zip)

**Comment by d41k4n** [comment]
Does it work with OrthoXP 1.3?

**Comment by mmaechtel** [comment]
Yes, with 1,3 no problem at all

**Comment by mmaechtel** [comment]
When i use a custom_dem it's also working but not with the default 'custom_dem' (e.g. empty) settings

**Comment by mmaechtel** [comment]
ok, will try it. Many thanks 👍

**Comment by Ricky1975** [comment]
Same error here. But also with a fresh 1.3. 
I have no 1v3 with "old" height data to check with.

**Comment by d41k4n** [comment]
IMO the cause is similar to what I wrote in https://github.com/oscarpilote/Ortho4XP/issues/228. Not much you can do apart from selecting a different DEM source or manually downloading the lower res 3" DEM from https://viewfinderpanoramas.org/dem3/L32.zip and extracting the missing .hgt's to the appropriate subfolder(s) in Elevation_data.

**Comment by d41k4n** [comment]
However, for Europe in particular I highly recommend manually downloading and installing the much superior [LiDAR DTMs provided by Sonny](https://sonny.4lima.de/).

**Comment by mmaechtel** [comment]
Now works great again with Lidar DTMs from Sonny. Many thanks for this great link to more precise data :)

**Comment by w8sl** [comment]
See comment:
https://github.com/oscarpilote/Ortho4XP/issues/228#issuecomment-2002318083

**Comment by scriptPilot** [comment]
Following the [install guide for MacOS](https://github.com/oscarpilote/Ortho4XP/issues/210#issuecomment-1795356672) I also have flat terrain as a result.

I found the following error in the logs, but the named config field is not available in the config window:

```
ERROR: file  Earth nav data/+40+000/+45+007.dsf absent.
Recall that the overlay source directory needs to be set  in the config window first.
```

The elevation data seems to be downloaded correctly.

<img width="223" alt="Bildschirmfoto 2024-03-22 um 10 34 06" src="https://github.com/oscarpilote/Ortho4XP/assets/19615586/eb573de9-4e7d-433d-b3aa-56dd8506d95e">

Any idea how to solve it?

**Comment by scriptPilot** [comment]
> When i use a custom_dem it's also working but not with the default 'custom_dem' (e.g. empty) settings

With Lidar DTMs from Sonny, is it required to select for each tile a new .hgt file and start the process for a single tile only?
Or it it possible to download the whole folder from Google and automatize its usage to create a bunch of tiles at once?

**Comment by scriptPilot** [comment]
> The error message is unrelated to the topic discussed here and possible workarounds were already mentioned earlier.

Alright, I've created a new issue for the error message above.
https://github.com/oscarpilote/Ortho4XP/issues/239

**Comment by d41k4n** [comment]
> > When i use a custom_dem it's also working but not with the default 'custom_dem' (e.g. empty) settings
> 
> With Lidar DTMs from Sonny, is it required to select for each tile a new .hgt file and start the process for a single tile only? Or it it possible to download the whole folder from Google and automatize its usage to create a bunch of tiles at once?

If you copy the .hgt files into the right folder(s) under Elevation_data you can leave custom_DEM  empty and create tikes in batch mode as usual.

If you need help with installing Sonny's DTM I suggest reading/posting here:

https://forums.x-plane.org/index.php?/forums/topic/165525-sonnys-lidar-digital-terrain-models-of-europe/

**Comment by scriptPilot** [comment]
Thanks for the quick and helpful responses, @d41k4n!

**Comment by scriptPilot** [comment]
Example for N45E007 ... the files are downloaded and read but +265 max altitude seems not reasonable for that tile. And loading the Sim results in a more or less flat tile in that area.

````
Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+40+000/N45E007.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N45E006.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N45E008.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N44E007.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N44E006.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N46E007.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N46E006.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40+000/N46E008.hgt from Viewfinderpanoramas (J. de Ferranti).
    * Min altitude: 0.0 , Max altitude: 265.33334 , Mean: 0.021674784
  ````

<img width="243" alt="Bildschirmfoto 2024-03-30 um 21 47 19" src="https://github.com/oscarpilote/Ortho4XP/assets/19615586/225c070f-f9ba-47db-bcf2-bef1555672b9">

**Comment by scriptPilot** [comment]
What I am wondering also is that the hgt files are downloaded again on each run for the same tile.
Is that by design or should they be reused like OSM or satellite images?

**Comment by w8sl** [comment]
Elevation data from Viewfinder Panoramas can only be downloaded in chunks of 24 tiles. 
Direct tile downloads based on latitude and longitude are not supported anymore. 

This part of code is deprecated:

 if (lat, lon) in (
            (44, 5),
            (45, 5),
            (46, 5),
            (43, 6),
            (44, 6),
            (45, 6),
            (46, 6),
            (47, 6),
            (43, 7),
            (44, 7),
            (45, 7),
            (46, 7),
            (47, 7),
            (45, 8),
            (46, 8),
            (47, 8),
            (45, 9),
            (46, 9),
            (47, 9),
            (45, 10),
            (46, 10),
            (47, 10),
            (45, 11),
            (46, 11),
            (47, 11),
            (45, 12),
            (46, 12),
            (47, 12),
            (46, 13),
            (47, 13),
            (46, 14),
            (47, 14),
            (46, 15),
            (47, 15),
        ):
            resol = 1
            url = (
                "http://viewfinderpanoramas.org/dem1/"
                + os.path.basename(FNAMES.base_file_name(lat, lon)).lower()
                + ".zip"
            )


Above tiles belong to:
   **"L31",  "L32",  "L33",  "K32",**


The correct syntax is:


if source == "View":
        # Viewfinderpanorama grouping of files and resolutions is a
        # bit complicated...

        deferranti_nbr = 31 + lon // 6
        if deferranti_nbr < 10:
            deferranti_nbr = "0" + str(deferranti_nbr)
        else:
            deferranti_nbr = str(deferranti_nbr)
        alphabet = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        deferranti_letter = (
            alphabet[lat // 4] if lat >= 0 else alphabet[(-1 - lat) // 4]
        )
        if lat < 0:
            deferranti_letter = "S" + deferranti_letter
        if deferranti_letter + deferranti_nbr in (
                "L31",
                "L32",
                "L33",
                "K32",
                "O31",
                "P31",
                "N32",
                "O32",
                "P32",
                "Q32",
                "N33",
                "O33",
                "P33",
                "Q33",
                "R33",
                "O34",
                "P34",
                "Q34",
                "R34",
                "O35",
                "P35",
                "Q35",
                "R35",
                "P36",
                "Q36",
                "R36",
            ):
                resol = 1
        else:
                resol = 3
        url = (
                "http://viewfinderpanoramas.org/dem"
                + str(resol)
                + "/"
                + deferranti_letter
                + deferranti_nbr
                + ".zip"
            )

**Comment by d41k4n** [comment]
@w8sl Appreciate the feedback. 

It would be helpful if you could create a pull-request that addresses this issue instead of pasting code in comments.

**Comment by w8sl** [comment]
@d41k4n Appreciate your feedback as well!
Tried my best.
Could not resist to update requirements

**Comment by w8sl** [comment]
For tile +47+1 I get: Min altitude: 52.0 , Max altitude: 258.6667 , Mean: 116.521545 from Viewfinder Panoramas 1" elevation data.  What version of Ortho4XP are you using?
Crash has been discussed here: https://github.com/oscarpilote/Ortho4XP/issues/260

**Comment by TheA321Channel** [comment]
> For tile +47+1 I get: Min altitude: 52.0 , Max altitude: 258.6667 , Mean: 116.521545 from Viewfinder Panoramas 1" elevation data. What version of Ortho4XP are you using? Crash has been discussed here: #260 Water in tile +47+1 is partially 2d/partially3d - as far I can see. It is how bathymetry data is coded in XP12 for this region.

Actually I meant to write +47+09 (with lake of constance) I have no idea how I got to 1 😂 
For lake of constance, the water is fully 3d, at least without Orthos.. Also, I'm using V1.4 with XP12 water tech option

**Comment by w8sl** [comment]
Tile +47 +009 is affected by problem fixed with #272  Update your src/O4_DEM_Utils.py file from pull request or download from source repisitory: *https://github.com/w8sl/Ortho4XP/tree/Fix_download_elevation_data*
Sonny´s .hgt file should work even better. Try with: 
**use_masks_for_inland = True**
**imprint_masks_to_dds = False**

**Comment by TheA321Channel** [comment]
Thanks; I got the file and I'm downloading the tile right now. Will give an update

**Comment by TheA321Channel** [comment]
Okay so I made the tile, it all works but water is still not 3d, I don't know what's causing that. At least it doesn't crash anymore, thank you

**Comment by w8sl** [comment]
I have done a quick test with:

water_tech: XP12
use_masks_for_inland = True
imprint_masks_to_dds = False

All other settings default.  Water is  3D on my end.

**Comment by TheA321Channel** [comment]
So I followed your steps and it is still not 3d.. Very strange
![image](https://github.com/user-attachments/assets/3b78dbad-a9c8-459d-96e3-2312cb21ba93)

**Comment by w8sl** [comment]
What is the exact location?

**Comment by TheA321Channel** [comment]
![image](https://github.com/user-attachments/assets/ee374cac-e8ea-441a-8d42-1a18269681ee)
Approx. at Echo

**Comment by w8sl** [comment]
It is looks very 3D with attached setting:

![LSZR 3D Water](https://github.com/user-attachments/assets/ff4bb92f-b309-4e30-8818-390aacbb36f2)
![Settings 3D water](https://github.com/user-attachments/assets/1647ee4c-7d95-41c3-a54a-afa1c462f38a)

You may eventually need to look in XP12 log.txt for errors (best done without plugins and other sceneries incl. X-World)

**Comment by TheA321Channel** [comment]
Well I checked my log with a few plugins and removed X-World and there were no errors when I removed that, however the waves still aren't 3d.. Is it possible I've messed up the actual Ortho4XP installation? And here's the XP12 log in case I've missed something 
[Log.txt](https://github.com/user-attachments/files/16322436/Log.txt)

**Comment by TheA321Channel** [comment]
And this is what I get in the cmd:

PS C:\Users\levi_\Desktop\X-Plane\Ortho4XP-master\Ortho4XP-master> Python Ortho4XP.py

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 73197 bytes (72 KiB)

Extracting archive: .\tmp\+47+009.dsf.7z
--
Path = .\tmp\+47+009.dsf.7z
Type = 7z
Physical Size = 73197
Headers Size = 130
Method = LZMA:192k
Solid = -
Blocks = 1

Everything is Ok

Size:       153756
Compressed: 73197
Exception in thread Thread-7 (build_dsf):
Traceback (most recent call last):
  File "C:\Users\levi_\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\levi_\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\levi_\Desktop\X-Plane\Ortho4XP-master\Ortho4XP-master\.\src\O4_DSF_Utils.py", line 1082, in build_dsf
    (bDEMN, bDEMS) = extract_elevation_and_bathymetry_data(tile.lat, tile.lon)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\levi_\Desktop\X-Plane\Ortho4XP-master\Ortho4XP-master\.\src\O4_DSF_Utils.py", line 458, in extract_elevation_and_bathymetry_data
    return (bDEMN, bDEMS)
                   ^^^^^
UnboundLocalError: cannot access local variable 'bDEMS' where it is not associated with a value

**Comment by TheA321Channel** [comment]
-> Encoding of the DSF file
     Final nbr of nodes: 1856926
     Extracting some rasters from X-Plane's Global Scenery
 *Activating DSF file.
ERROR : could not rename DSF file, tile is not actived.

Completed in 3m27sec.
_________________________________________________________________________________________________

wow I'm an unlucky soul???

**Comment by w8sl** [comment]
(bDEMN, bDEMS) = extract_elevation_and_bathymetry_data(tile.lat, tile.lon)
After deleting Orto4XP.cfg, custom_overlay_src must be set again to:  /X-Plane 12/Global Scenery/X-Plane 12 Global Scenery
Also overpas_server_choice can be changed to the one working best. I am sorry for incomplete information!

**Comment by TheA321Channel** [comment]
![image](https://github.com/user-attachments/assets/de01c13f-851c-495a-9910-7a938c9c02cb)
Thank you soooo much for helping me out!!! Finally it works 👍
