### ISSUE TITLE
zOrtho4XP_+46-072 fail because of the coastline

### ISSUE THREAD

**Issue by akhenakh** [oscarpilote/Ortho4XP#33]
Next to Quebec City, there is an island inside the Saint Laurent river.

For some reasons ortho4xp is failing and only download images for this island.

```
11M     Tiles/zOrtho4XP_+46-072/textures/92256_79328_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92256_79344_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92256_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92272_79328_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92272_79344_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92272_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92288_79312_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92288_79328_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92288_79344_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92288_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92304_79296_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92304_79312_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92304_79328_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92304_79344_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92304_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92320_79280_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92320_79296_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92320_79312_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92320_79328_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92320_79344_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92320_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79264_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79280_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79296_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79312_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79328_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79344_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92336_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92352_79264_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92352_79280_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92352_79296_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92352_79312_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92352_79328_BI18.dds
9.8M    Tiles/zOrtho4XP_+46-072/textures/92352_79344_BI18.dds
9.6M    Tiles/zOrtho4XP_+46-072/textures/92352_79360_BI18.dds
11M     Tiles/zOrtho4XP_+46-072/textures/92368_79264_BI18.dds
```

tested with Ortho4XP_v130.py master at b5fc9be0659134c3e90cbc48bc70d08a2963db76

**Comment by oscarpilote** [comment]
Don't get such error here now. Probably OSM was fixed (coastline with wrong orientation) since then.

**Comment by akhenakh** [comment]
restarted from a brand new ortho4xp directory so assuming no cache, with the exact same result.
BI 18

**Comment by akhenakh** [comment]
Still happening on a different computer could it be this ?  `*  Fleuve Saint-Laurent, Estuaire fluvial will be masked like the sea due to its large area of 757 km^2.`
```
Step 1 : Building vector data for tile +46-072 : 
--------

-> Dealing with airports
    * Downloading OSM data for ('node["aeroway"]', 'way["aeroway"]', 'rel["aeroway"]')
   CTR6   St-Basile (Marcotte) Airport                                 1 runway , lat= 46.78, lon= -71.83
   CYQB   Québec City Jean Lesage International Airport                2 runways, lat= 46.78, lon= -71.40
   ****   Thetford Mines Airport                                       1 runway , lat= 46.05, lon= -71.26
   ****   Victoriaville Airport                                        1 runway , lat= 46.11, lon= -71.93
   ****   ****                                                         2 runways, lat= 46.69, lon= -71.15
   Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+40-080/N46W072.hgt from Viewfinderpanoramas (J. de Ferranti).
    Downloading  ./Elevation_data/+40-080/N46W073.hgt from Viewfinderpanoramas (J. de Ferranti).
    * Min altitude: 0.0 , Max altitude: 694.0 , Mean: 197.15488
   Auto-patched 7 runways and 83 pieces of taxiway.
   Flattened 22 helipads.
   Number of edges at this point: 3604
-> Dealing with roads
    * Downloading OSM data for way["highway"="motorway"]
    * Downloading OSM data for way["highway"="trunk"]
    * Downloading OSM data for way["highway"="primary"]
    * Downloading OSM data for way["highway"="secondary"]
    * Downloading OSM data for way["railway"="rail"]
    * Downloading OSM data for way["railway"="narrow_gauge"]
    * Checking which large roads need levelling.
    * Buffering banked road network as multipolygon.
      Encoding it.
    * Encoding the remaining primary road network as linestrings.
   Number of edges at this point: 38146
-> Dealing with coastline
    * Downloading OSM data for way["natural"="coastline"]
    * Encoding coastline.
    * Reconstructing its topology.
      Found  1 contiguous patch(es).
   Number of edges at this point: 38865
-> Dealing with inland water
    * Downloading OSM data for rel["natural"="water"]
    * Downloading OSM data for rel["waterway"="riverbank"]
    * Downloading OSM data for way["natural"="water"]
    * Downloading OSM data for way["waterway"="riverbank"]
    * Downloading OSM data for way["waterway"="dock"]
    * Building water multipolygon.
      *  Fleuve Saint-Laurent, Estuaire fluvial will be masked like the sea due to its large area of 757 km^2.
      Cleaning it.
      Encoding it.
      Separate treatment for larger pieces requiring masks.
      Encoding them.
   Number of edges at this point: 125847
-> Inserting edges related to the orthophotos grid
-> Inserting additional boundary edges for gluing
-> Transcription to the files  ./Tiles/zOrtho4XP_+46-072/Data+46-072.poly and .node

Final number of constrained edges : 178955

Completed in 2m1sec.
_________________________________________________________________________________________________

Step 2 : Building mesh for tile +46-072 : 
--------

-> Modifying curv_tol weight map according to runway locations.
-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from ./OSM_data/+40-080/+46-072/+46-072_coastline.osm.bz2
-> Start of the mesh algorithm Triangle4XP.
   Loading altitudes from DEM file.
   Loading curv_tol geographic weights.
   Computing curvatures from altitudes.
   Constructing Delaunay triangulation by divide-and-conquer method.
   Recovering segments in Delaunay triangulation.
   Spreading regional attributes.
   Adding Steiner points to enforce quality.
   Computing altitude and normal maps.
   Node file ./Tiles/zOrtho4XP_+46-072/Data+46-072.1.node written to disk.
   Tri file  ./Tiles/zOrtho4XP_+46-072/Data+46-072.1.ele  written to disk.

   Statistics:

   Input vertices: 155728
   Input segments: 178955
   Input holes: 0

   Mesh vertices: 194,587
                   -----------------
   Mesh triangles: ---> 380,444
                   -----------------
   Mesh edges: 575030
   Mesh exterior boundary edges: 8728
   Mesh interior boundary edges: 186768
   Mesh subsegments (constrained edges): 195496

-> Loading of the mesh computed by Triangle4XP.
-> Post processing of altitudes according to vector data
   Smoothing inland water.
   Smoothing of sea water.
   Treatment of airports, roads and patches.
-> Writing output nodes file.
-> Writing final mesh to the file ./Tiles/zOrtho4XP_+46-072/Data+46-072.mesh

Completed in 6.10sec.
_________________________________________________________________________________________________

Step 2.5 : Building masks for tile +46-072 : 
--------

-> Deleting existing masks
-> Reading mesh data
   *  ./Tiles/zOrtho4XP_+46-072/Data+46-072.mesh
-> Construction of the masks
   Skipping 5776_4912.png
   Skipping 5760_4912.png
   Skipping 5824_4912.png
   Skipping 5808_4928.png
   Skipping 5760_4928.png
   Creating 5776_4960.png
   Skipping 5824_4928.png
   Skipping 5808_4912.png
   Skipping 5776_4928.png
   Creating 5776_4944.png
   Skipping 5824_4944.png
   Creating 5760_4944.png
   Skipping 5808_4944.png
   Skipping 5792_4944.png
   Skipping 5792_4960.png
   Skipping 5792_4912.png
   Creating 5760_4960.png
     Ends-up being discarded.
     Ends-up being discarded.
   Skipping 5824_4960.png
   Skipping 5808_4960.png
   Skipping 5792_4928.png

Completed in 22.02sec.
_________________________________________________________________________________________________

Step 3 : Building DSF/Imagery for tile +46-072 : 
--------

-> Initializing providers with potential data on this tile.
-> Opening download queue.
-> Opening convert queue and 4 conversion workers.
-> Computing the pool quadtree
     Number of buckets: 64
     Average depth: 3.0 , Average bucket size: 3047.515625
     Largest depth: 3
   Downloading missing orthophoto 46176_39632_BI17.jpg
   Converting orthophoto(s) to build texture 46176_39632_BI17.dds.
   Downloading missing orthophoto 46176_39664_BI17.jpg
   Downloading missing orthophoto 46176_39648_BI17.jpg
   Converting orthophoto(s) to build texture 46176_39664_BI17.dds.
   Downloading missing orthophoto 46176_39680_BI17.jpg
   Converting orthophoto(s) to build texture 46176_39648_BI17.dds.
-> Encoding of the DSF file
     Final nbr of nodes: 198036
   Converting orthophoto(s) to build texture 46176_39680_BI17.dds.
   Downloading missing orthophoto 46160_39632_BI17.jpg
     DSF file encoded, total size is : 4388245 bytes (4.2M)
   Downloading missing orthophoto 46128_39680_BI17.jpg
   Downloading missing orthophoto 46128_39664_BI17.jpg
   Downloading missing orthophoto 46160_39648_BI17.jpg
   Downloading missing orthophoto 46144_39648_BI17.jpg
   Downloading missing orthophoto 46160_39680_BI17.jpg
   Downloading missing orthophoto 46144_39664_BI17.jpg
   Downloading missing orthophoto 46160_39664_BI17.jpg
   Downloading missing orthophoto 46144_39680_BI17.jpg
 *Download of textures completed.
 *Activating DSF file.

Completed in 25.49sec.
```

**Comment by d41k4n** [comment]
I fixed  some OSM issues with coastlines in that area about 4 months ago:
https://www.openstreetmap.org/changeset/65303581

I couldn't reproduce the problem anymore.
